config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases  
  # resources :approvals

  resources :users do
    collection { post :import }  # こちらが追加されます


    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit_notice_info'
      get 'attendances/edit_one_month'
      # patch 'attendances/update_one_month' # この行が追加対象です。
      get 'attendances/working'
      get 'attendances/_fotm_overwork_info'
      # get '_approvals_edit'
      get 'approvals_edit'
      patch 'users/approval_of_monthly_applications'    
      put 'users/create_send'    
      get '/users/:id/edit_basic_info', to: 'users#edit_basic_info'
      get 'users/:id/pending_requests', to: 'users#pending_requests', as: 'pending_requests'
      # get 'apply_for_approval'
      # resources :users, only: [:show, :edit, :update]  # showアクションがcurrent_userのページに該当する場合
    end

    
    
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # has_many :applied_attendances, class_name: 'Attendance', foreign_key: 'applied_user_id'
  # accepts_nested_attributes_for :attendances
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  # validates :employee_number, presence: true, uniqueness: true
  # validates :employee_number, presence: true, allow_blank: true
  validates :basic_work_time, presence: true
  validates :work_time, presence: true
  # validates :designated_work_start_time
  # validates :designated_work_end_time
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
   def self.search(search) #self.はUser.を意味する
     if search
      @users = User.where(['name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
     else
       User.all #全て表示させる
     end   
   end   
   
  def self.import(file)
    failed_emails = []
  
    CSV.foreach(file.path, headers: true) do |row|
      existing_user = User.find_by(email: row["email"])
      
      if existing_user
        failed_emails << row['email']
      else
        user = User.new
        user.attributes = row.to_hash.slice(*["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"])
        user.save!
      end
    end
    
    failed_emails
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :approvals_edit]
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:show, :approvals_edit]
  before_action :admin_or_correct_user, only: :show


  def pending_requests
    @user = User.find(params[:id])
    @first_day = params[:date] ? Date.parse(params[:date]) : Date.today.beginning_of_month
    @attendances = @user.attendances.where(worked_on: @first_day.all_month)
    render partial: 'pending_requests_modal', locals: { user: @user, attendances: @attendances }
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit
    end
  end





  

  
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  
  def import
    failed_emails = User.import(params[:file])
  
    if failed_emails.empty?
      flash[:success] = 'インポートに成功しました。'
    else
      flash[:danger] = "メールアドレス #{failed_emails.join(', ')} はすでに存在します。"
    end
    
    redirect_to users_path
  end


  def show
    if current_user.admin?
      redirect_to root_url
    else
      @attendance = Attendance.find(params[:id])
      @users = User.all
      @worked_sum = @attendances.where.not(started_at: nil).count
      @superiors = User.where(superior: true).where.not(id: @user.id)

      @notice_users = User.where(id: Attendance.where.not(schedule: nil).select(:user_id)).where.not(id: current_user)
      @notice_users.each do |user|
        # 何らかの処理
      end

      @attendances_list = Attendance.where.not(schedule: nil).where(overtime_check: false).where(confirmation: current_user.name)
      @endtime_notice_sum = @attendances_list.count
      @attendances_list.each do |att_notice|
        @att_notice = att_notice
      end

      @att_update_list = Attendance.where(attendance_change_check: false).where(attendance_change_flag: true).where(confirmation: current_user.name)
      @att_update_sum = @att_update_list.count
      @att_update_list.each do |att_up|
        @att_up = att_up
      end

      @attendance = Attendance.find_by(worked_on: @first_day)

      # @approval_list を現在ログインしているユーザーが承認を担当する申請情報でフィルタリング
      @approval_list = Attendance.where(month_request_superior_id: current_user.id, month_request_status: '申請中')
      # 申請中の件数をカウント
      @applying_month_count = @approval_list.count

      @approval_list.each do |approval|
        @approval = approval
        @approval_superior = User.find_by(id: @approval.superior_id)
      end
    end

    # approval_of_monthly_applicationsアクションを呼び出す
    if params[:trigger] == 'approval'
      approval_of_monthly_applications
    end
  end

  def approval_of_monthly_applications
    @attendance = Attendance.find(params[:id])

    if params[:attendance][:superior_id].blank?
      flash[:danger] = '上長を選択してください。'
      redirect_to user_path(current_user)
    else
      
      if @attendance.update(month_request_superior_id: params[:attendance][:superior_id], month_request_status: '申請中')
        flash[:success] = "申請が更新されました。"
        redirect_to user_path(current_user)
      else
        flash[:danger] = "申請の更新に失敗しました。"
        redirect_to user_path(current_user)
      end
    end
  end

  def approvals_edit
  end


  def edit_one_month
  end  
  


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
    
    # attendance パラメータの存在をチェック
    if params[:attendance].present?
      @attendance = Attendance.new(attendance_params)
      if @attendance.save
        redirect_to attendances_path, notice: '申請が完了しました。'
      else
        render :new
      end
    end
  end

  def edit

  end



  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  

  private  
    


  def approval_params
    params.require(:attendance).permit(:month_request_superior_id, :month_request_status)
  end

  def user_params
    params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation)
  end

  def basic_info_params
    params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :basic_work_time, :designated_work_start_time, :designated_work_end_time)
  end

  # フォームから送信されるパラメータの安全な処理
  def attendance_params
    # 必要なパラメータを許可
    params.require(:attendance).permit(:superior_id, :worked_on, :confirmation_status)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_approvals_edit.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title"></h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <table class="frame">
         <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <h1><%= @userからの１カ月分の勤怠申請 %></h1>  
            <% @attendances.each do |day| %>
                <thead>
                  <tr>
                    <th width="100">月</th>
                    <th width="300">指示者確認㊞</th>
                    <th width="100">変更</th>
                    <th width="300">勤怠を確認する</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td width="100"><%= l(day.worked_on, format: "%Y") %>月</td>
                    <td width="300"><%= f.select :confirmation_status, [["なし", 0],["申請中", 1],["承認", 2],["否認",3]] %></td>
                    <td width="100">1</td>
                    <td width="300"><%= link_to "確認", class: "btn btn-primary" %></td>
                  </tr>                  
                </tbody>
             <% end %>
             </table>
            <div class="center">
              <%= f.submit "変更を送信する", class: "btn btn-primary" %>
            </div> 
          <% end %>
        <!--</div>-->
      </div>
    </div>
  </div>
</div>

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
      <h1 class="modal-title">基本情報の更新</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>

            <%= f.label :name, class: "label-#{yield(:class_text)}" %>
            <p><%= @user.name %></p>

            <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
            <%= f.text_field :affiliation, class: "form-control" %>

            <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_work_time, class: "form-control" %>

            <%= f.label :work_time, class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
              <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                キャンセル
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_edit_notice_info.html.erb
          <%= form_with(model: user, url: update_basic_info_user_path(user), local: true, method: :patch) do |f| %>

      
          <%= f.label :"名前", class: "label-user--edit" %>
          <%= f.text_field :name, class: "form-control" %>
      
          <%= f.label :"メールアドレス", class: "label-user--edit" %>
          <%= f.email_field :email, class: "form-control" %>
      
          <%= f.label :"所属", class: "label-user--edit" %>
          <%= f.text_field :affiliation, class: "form-control" %>
      
          <%= f.label :"社員番号", class: "label-user--edit" %>
          <%= f.number_field :employee_number, class: "form-control", min: 001, max: 020 %>
      
          <%= f.label :"カードID", class: "label-user--edit" %>
          <%= f.number_field :uid, class: "form-control", min: 001, max: 020 %>
      
          <%= f.label :"パスワード", class: "label-user--edit" %>
          <%= f.password_field :password, class: "form-control" %>
      
          <%= f.label :"基本勤務時間", class: "label-user--edit" %>
          <%= f.time_field :basic_work_time, class: "form-control" %>
      
          <%= f.label :"指定勤務開始時間", class: "label-user--edit" %>
          <%= f.time_field :designated_work_start_time, class: "form-control" %>
      
          <%= f.label :"指定勤務終了時間", class: "label-user--edit" %>
          <%= f.time_field :designated_work_end_time, class: "form-control" %>
          
          <%= f.submit "編集する", class: "btn btn-primary btn-block btn-user--edit" %>
          
          <% end %>
          

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_pending_requests_modal.html.erb
  <h2>申請中の件数</h2>
  <table>
    <thead>
      <tr>
        <th>日付</th>
        <th>開始時間</th>
        <th>終了時間</th>
        <th>ステータス</th>
      </tr>
    </thead>

app/views/users/approvals_edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'approvals_edit') %>");
$("#user-modal").modal("show");

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '編集') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>ユーザー一覧</h1>

<div class="row">
  <div class="col-lg-4">
    <%= form_tag import_users_path, multipart: true do %>
        <%= file_field_tag :file %>
        <div class="spacing">
        <span class="input-group-btn">
          <%= submit_tag "CSVをインポート", class: "btn btn-primary" %>
        </span>
        </div>        
        </div> 
    <% end %>
  </div>
</div>




<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <% @users.each do |user| %>
      <% unless user.admin? %>
 
    <%= link_to user.name, user %>
    <div class="bb">
    | <%= link_to "削除", user, method: :delete,
                    data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %>
    </div>                
          <thead>
          <div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                  <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=user.id %>"　button type="button" class="btn btn-primary btn-lg" >編集</a>
              </div>
              <div id="collapse<%=user.id %>" class="panel-collapse collapse in">
                <div class="panel-body">
            <%= render 'edit_notice_info', user:user %>
                </div>
              </div>
            </div>
          </thead>  
      <% end %>    
    <% end %>    
    
<!--モーダルウインドウ表示-->
<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td style="text-align: center;">
          <%= link_to content_tag(:span, "←", class: "arrow-box"), user_path(date: @first_day.prev_month) , class: "btn btn-primary" %>
          【<%= l(@first_day, format: :middle) %>】勤怠管理表
          <%= link_to content_tag(:span, "→", class: "arrow-box"), user_path(date: @first_day.next_month) , class: "btn btn-primary" %>
      </td>
      <td>
      <div class="i">指定勤務開始時間 <%= @attendance.started_at.strftime("%H:%M").gsub(':', '.') if @attendance.started_at.present? %></div>
      <div class="i">指定勤務終了時間 <%= @attendance.finished_at.strftime("%H:%M").gsub(':', '.') if @attendance.finished_at.present? %></div>
      </td>  
      <td colspan="3">基本時間：<%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日：<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名：<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.id %></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め：<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<% if current_user.superior == true %>
  <div class="various-notices">
    <div class="various-notice">
      <%= link_to "【所属長承認申請のお知らせ】", pending_requests_user_path(@user, date: @first_day), remote: true,
      class: "#{@applying_month_count == 0 ? "link-not-applying" : "link-applying"}", data: { popup: true } %>
      <% if @applying_month_count != 0 %>
        <a class="information-display"><%= "#{@applying_month_count}件の通知があります。" %></a>
      <% end %>
    </div>
  </div>
<% end %>



<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力","＃", class: "btn btn-primary" %>
<div class="item"><%= link_to "勤怠修正ログ（承認済）","＃", class: "btn btn-primary" %></div>  
</div>


<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>  	
     <tr>
      <th rowspan="4">残業申請</th>	
      <th rowspan="4">日付</th>	
      <th rowspan="4">曜日</th>	
     <tr>
      <th colspan="8">【実績】</th>	
      <th colspan="8">所定外勤務</th>	
     </tr>     
      <th colspan="3">出社</th>	
      <th colspan="3">退社</th>	
      <th rowspan="2">在社時間</th>	
      <th rowspan="2">備考</th>	
      <th colspan="2">終了予定時間</th>	
      <th rowspan="2">時間外時間</th>	
      <th rowspan="2">業務処理内容</th>	
      <th rowspan="2">指示者確認㊞</th>	
      
     </tr>	
     <tr>
      <td>時</td><td>分</td><td></td>
      <td>時</td><td>分</td><td></td>
      <td>時</td><td>分</td>
     </tr>
    </thead>

   <tbody>
    <% @attendances.each do |day| %>        <td><%= link_to "残業申請",attendances__fotm_overwork_info_user_path, class: "btn btn-primary" %></td>
        <td><%= l(day.worked_on, format: :short) %></td>
        <td class="<%= day.worked_on.wday == 6 ? 'saturday' : day.worked_on.wday == 0 ? 'sunday' : 'weekday' %>">
          <%= $days_of_the_week[day.worked_on.wday] %>
        </td>
        <td><%= day.started_at.floor_to(15.minutes).strftime("%H") if day.started_at.present? %></td>
        <td><%= day.started_at.floor_to(15.minutes).strftime("%M") if day.started_at.present? %></td>
        <td>
          <% if day.started_at.blank? && (btn_text = attendance_state(day)) %>
            <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>    
        <td><%= day.finished_at.floor_to(15.minutes).strftime("%H") if day.finished_at.present? %></td>
        <td><%= day.finished_at.floor_to(15.minutes).strftime("%M") if day.finished_at.present? %></td>
        <td>
        　<% if day.started_at.present? && day.finished_at.blank? && (btn_text = attendance_state(day)) %>
            <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
          <% end %>
        </td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <% rounded_started_at = day.started_at.floor_to(15.minutes) %>
            <% rounded_finished_at = day.finished_at.floor_to(15.minutes) %>
            <%= str_times = working_times(rounded_started_at, rounded_finished_at) %>
            <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
          <% end %>
        </td>        
        <td><%= day.note %></td>
        <!-- 終了予定時間（時） -->
        <td>
         <!--<　% if day.tomorrow_check == Ftrue %>-->
         <!--  <　%= day.schedule.tomorrow.strftime("%H") if day.schedule.present? %>-->
         <!--<　% else %>-->
         <!--  <　%= day.schedule.strftime("%H") if day.schedule.present? %>-->
         <!--<　% end %>-->
        </td>
        <!-- 終了予定時間（分） -->
        <td>
         <!--<　% if day.tomorrow_check == true %>-->
         <!--  <　%= day.schedule.floor_to(15.minutes).tomorrow.strftime("%M") if day.schedule.present? %>-->
         <!--<　% else %>-->
         <!--  <　%= day.schedule.floor_to(15.minutes).strftime("%M") if day.schedule.present? %>-->
         <!--<　% end %>-->
        </td>
        <td></td>
        <td></td>
        <td></td>        
      </tr>
      <% end %>
    </tbody>
    
    <tfoot>
      <tr>
        <td colspan="6"></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <td colspan="6"></td>
        <td>
         <% if current_user.present? %>
                <%= form_with(model: @attendance, url: users_approval_of_monthly_applications_user_path(@user), method: :patch, local: true) do |f| %>
                  <div class="approval">
                    <p class="approval-btn">
                      所属長承認:
                      <p class="approval-btn"> <%= f.select :superior_id, @superiors.map { |superior| [superior.name, superior.id] }, { include_blank: "上長を選択してください" }, class: "select" %></p>
                      <%= f.submit "申請", class: "btn btn-primary w-50" %>
                  </div>
                <% end %>
            <% end %>
          </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>