config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :bases  
  # resources :approvals

  resources :users do
    collection { post :import }  # こちらが追加されます


    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'edit_notice_info'
      get 'attendances/edit_one_month'
      # patch 'attendances/update_one_month' # この行が追加対象です。
      get 'attendances/working'
      get 'attendances/_fotm_overwork_info'
      # get '_approvals_edit'
      get 'approvals_edit'
      patch 'users/approval_of_monthly_applications'    
      put 'users/create_send'    
      get '/users/:id/edit_basic_info', to: 'users#edit_basic_info'
      get 'users/:id/pending_requests', to: 'users#pending_requests', as: 'pending_requests'
      # get 'apply_for_approval'
      # resources :users, only: [:show, :edit, :update]  # showアクションがcurrent_userのページに該当する場合
    end

    
    
    resources :attendances, only: :update
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  # belongs_to :applied_user, class_name: 'User', foreign_key: 'applied_user_id'

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  # validates :superior_id, presence: { message: '上長を選択してください' }
  enum confirmation_status: { なし: 0, 申請中: 1, 承認: 2, 否認: 3 }
  


  # 出勤時間が存在しない場合、退勤時間は無効
  # validate :designated_work_end_time_is_invalid_without_a_designated_work_start_time
  # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  # validate :designated_work_start_time_than_designated_work_end_time_fast_if_invalid

  # def designated_work_end_time_is_invalid_without_a_designated_work_start_time
  #   errors.add(:designated_work_start_time, "が必要です") if designated_work_start_time.blank? && designated_work_end_time.present?
  # end

  # def designated_work_start_time_than_designated_work_end_time_fast_if_invalid
  #   if designated_work_start_time.present? && designated_work_end_time.present?
  #     errors.add(:designated_work_start_time, "より早い退勤時間は無効です") if designated_work_start_time > designated_work_end_time
  #   end
  # end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_or_correct_user, only: [:update, :update_one_month, :edit_one_month]
  before_action :set_one_month, only: :edit_one_month
  # before_action :superior_user, only: [:edit_overtime_info, :edit_change_attendance]

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"
  
  def working
    @attendances = Attendance.where(worked_on: Date.current).where.not(designated_work_start_time: nil).where(designated_work_end_time: nil)
    @users = User.all.includes(:attendances)
    
    @users.each do |user|
      user.employee_number = (user.id * 111).to_s
      user.save
    end
  end  
  

# def set_employee_number
#   self.employee_number = (id * 111).to_s  # IDに100を掛けて文字列に変換して設定
#   save
# end  

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.floor_to(15.minutes).change(sec: 0)) 
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.floor_to(15.minutes).change(sec: 0))  
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
    
  def show
  end

  

  def edit_one_month
  end


  def update_one_month
      ActiveRecord::Base.transaction do
        attendances_params.each do |id, item|
          if item[:designated_work_start_time].present? && item[:designated_work_end_time].blank?
            flash[:danger] = "退勤も更新してください"
            redirect_to attendances_edit_one_month_user_url(date: params[:date])and return
          end  

            attendance = Attendance.find(id)
            attendance.update_attributes!(item)
        end
      end
      # flash[:success] = "1ヶ月分の勤怠情報を更新しました。"
      redirect_to user_url(date: params[:date])and return
  rescue ActiveRecord::RecordInvalid
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end


  private

    # 1ヶ月分の勤怠情報を扱います。
  def attendances_params
    params.require(:user).permit(attendances: [:designated_work_start_time, :designated_work_end_time, :note])[:attendances]
  end

  # def updated_time_params
  #   params.require(:user).permit(attendances: [:designated_work_start_time, :designated_work_end_time, :tommorow_check, :note, :name])[:attendances]
  # end
    # beforeフィルター


    # 管理権限者、または現在ログインしているユーザーを許可します。
  def admin_or_correct_user
    @user = User.find(params[:user_id]) if @user.blank?
    unless current_user == @user || current_user.admin?
      flash[:danger] = "編集権限がありません。"
      redirect_to(root_url)
    end  
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper

  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出勤' if attendance.started_at.nil?
      return '退勤' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    return false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
    # sprintf("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  def convert_basic_time_to_number(basic_work_time)
    # ここでbasic_time（例："8:00"）を数値（例：8.0）に変換する処理
    # 今回は既に数値形式（例：8.0）であると仮定
   basic_work_time.to_f
  end
  

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
#   def times(start, finish)
#     format("%.2f", (((finish - start) / 60) / 60.0))
#   end
  
#   def format_min(time)
#     format("%.2d",((time.strftime('%M').to_i / 15).round)* 15)
      
#   end
  
#   def working_times(start, finish)
#     format("%.2f", (((finish - start) / 60) / 60.0))
#   end


#   def working_overtimes(start, finish)
#     format("%.2f", (((finish - start) / 60) / 60.0)-(60.0*8))
#   end
# end
  
  
  # class Time
  #   def floor_to(seconds)
  #     Time.at((self.to_f / seconds).floor * seconds)
  #   end
  # end
end

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出勤時間</th>
          <th>退勤時間</th>
          <th>在社時間</th>
          <th>備考</th>
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |attendance| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td><%= $days_of_the_week[day.worked_on.wday] %></td>
              <% if Date.current < day.worked_on %>
                <td><%= attendance.time_field :designated_work_start_time, readonly: true, class: "form-control" %></td>
                <td><%= attendance.time_field :designated_work_end_time, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= attendance.time_field :designated_work_start_time, class: "form-control" %></td>
                <td><%= attendance.time_field :designated_work_end_time, class: "form-control" %></td>
              <% end %>
              <td>
                <% if day.designated_work_start_time.present? && day.designated_work_end_time.present? %>
                  <%= working_times(day.designated_work_start_time, day.designated_work_end_time) %>
                <% end %>
              </td>
              <td><%= attendance.text_field :note, class: "form-control" %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= f.submit "まとめて更新", class: "btn btn-lg btn-primary" %>
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
  </div>
<% end %>

app/views/attendances/working.html.erb
<% provide(:title, "出勤中社員一覧") %>
<h1>出勤中社員一覧</h1>

<div>
  <table class="table table-bordered table-condensed table-hover text-center table-striped" id="index_attendance">
    <thead>
      <tr>
        <th class="text-center">社員番号</th>
        <th class="text-center">名前</th>
      </tr>  
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <% user.attendances.each do |attendance| %>
          <% if attendance.designated_work_start_time.present? && attendance.designated_work_end_time.nil? && attendance.worked_on && Date.current %>
        <tr>
          <td><%= user.employee_number %></td>
          <td><%= user.name %></td>
        </tr>
        <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<!--today = DateTime.now-->